### ISSUE TITLE
Fails install with current version kreait/firebase-php

### ISSUE THREAD

**Issue by arnoldsmyth** [tattersoftware/codeigniter4-firebase#25]
Here is the error that I get:
tatter/firebase v1.3.0 requires kreait/firebase-php ^5.0 -> found kreait/firebase-php[5.0.0, ..., 5.26.1] but it conflicts with your root composer.json require (^6.0).

**Comment by MGatner** [comment]
I haven't had a chance to check actual compatibility. The Dependabot PR (https://github.com/tattersoftware/codeigniter4-firebase/pull/24) failed CI/CD checks - I suspect they are just from outdated tool configurations but without looking through the logs I can't be sure. Feel free to test compatibility yourself and resolve any issues, or it will have to wait for me to get around to the updates.

**Comment by MGatner** [comment]
#26

**Comment by MGatner** [comment]
It looks to me like there is an issue upstream with Protobuf that will prohibit `8.1` support, but I will wrap up this PR soon and have this library compatible regardless.

**Comment by MGatner** [comment]
Closed by #26
